SET search_path TO user_schema;

CREATE TABLE SERVERINFO(
	ID SERIAL NOT NULL PRIMARY KEY,
	SERVER_IP CHARACTER VARYING(255),
	HOST_NAME CHARACTER VARYING(255),
	SERVER_CATEGORY CHARACTER VARYING(255),
	ENV_CATEGORY CHARACTER VARYING(255),
	ENVIRONMENT_NAME CHARACTER VARYING(255),
	PRODUCT_CATEGORY CHARACTER VARYING(255),
	PRODUCT_NAME CHARACTER VARYING(255),
	DEVELOPMENT_STREAM CHARACTER VARYING(255),
	ASSIGNED_TO CHARACTER VARYING(255),
	DATABASE_ENDPOINT CHARACTER VARYING(255),
	
	PROGRAM_NAME CHARACTER VARYING(255),
	SUB_DEPARTMENT CHARACTER VARYING(255),
	COMMENTS CHARACTER VARYING(2000),
	LAST_UPDATED TIMESTAMP DEFAULT NOW()
);
